name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json
        
    - name: Install dependencies
      run: |
        cd web
        npm ci
        
    - name: Build
      env:
        VITE_GOOGLE_SHEETS_API_KEY: ${{ secrets.VITE_GOOGLE_SHEETS_API_KEY }}
        VITE_GOOGLE_SHEETS_CLIENT_ID: ${{ secrets.VITE_GOOGLE_SHEETS_CLIENT_ID }}
        VITE_GOOGLE_SHEETS_CLIENT_SECRET: ${{ secrets.VITE_GOOGLE_SHEETS_CLIENT_SECRET }}
        VITE_SPREADSHEET_ID: ${{ secrets.VITE_SPREADSHEET_ID }}
        VITE_APP_NAME: Scrub Shop Road App
        VITE_APP_VERSION: 1.0.0
      run: |
        cd web
        npm run build
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web/dist
        cname: # Add your custom domain here if you have one 